version: "3.7"

services:
  db:
    image: mongo:4.2.5
    ports:
      - "27017:27017"
    volumes:
      - /tmp/reviews:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
